/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 10
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_BANG = 2,
  anon_sym_QMARK_BANG = 3,
  anon_sym_QMARK = 4,
  anon_sym_AT = 5,
  anon_sym_BSLASH = 6,
  anon_sym_u03bb = 7,
  anon_sym_u2200 = 8,
  anon_sym_u2203_BANG = 9,
  anon_sym_u2203 = 10,
  anon_sym_if = 11,
  anon_sym_then = 12,
  anon_sym_else = 13,
  anon_sym_let = 14,
  anon_sym_in = 15,
  anon_sym_and = 16,
  anon_sym_case = 17,
  anon_sym_of = 18,
  anon_sym_do = 19,
  anon_sym_od = 20,
  anon_sym_with = 21,
  anon_sym_T = 22,
  anon_sym_F = 23,
  sym_antiquotation = 24,
  sym_number = 25,
  sym_string = 26,
  sym_char = 27,
  sym_type_var = 28,
  anon_sym_SLASH_BSLASH = 29,
  anon_sym_BSLASH_SLASH = 30,
  aux_sym_operator_token1 = 31,
  aux_sym_operator_token2 = 32,
  anon_sym_LPAREN = 33,
  anon_sym_RPAREN = 34,
  anon_sym_LBRACK = 35,
  anon_sym_RBRACK = 36,
  anon_sym_LBRACE = 37,
  anon_sym_RBRACE = 38,
  anon_sym_COMMA = 39,
  anon_sym_SEMI = 40,
  sym_comment = 41,
  sym_source_file = 42,
  sym__token = 43,
  sym_binder = 44,
  sym_keyword = 45,
  sym_boolean = 46,
  sym_operator = 47,
  sym_punctuation = 48,
  aux_sym_source_file_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_BANG] = "!",
  [anon_sym_QMARK_BANG] = "\?!",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AT] = "@",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_u03bb] = "\u03bb",
  [anon_sym_u2200] = "\u2200",
  [anon_sym_u2203_BANG] = "\u2203!",
  [anon_sym_u2203] = "\u2203",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_let] = "let",
  [anon_sym_in] = "in",
  [anon_sym_and] = "and",
  [anon_sym_case] = "case",
  [anon_sym_of] = "of",
  [anon_sym_do] = "do",
  [anon_sym_od] = "od",
  [anon_sym_with] = "with",
  [anon_sym_T] = "T",
  [anon_sym_F] = "F",
  [sym_antiquotation] = "antiquotation",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_char] = "char",
  [sym_type_var] = "type_var",
  [anon_sym_SLASH_BSLASH] = "/\\",
  [anon_sym_BSLASH_SLASH] = "\\/",
  [aux_sym_operator_token1] = "operator_token1",
  [aux_sym_operator_token2] = "operator_token2",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_binder] = "binder",
  [sym_keyword] = "keyword",
  [sym_boolean] = "boolean",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_QMARK_BANG] = anon_sym_QMARK_BANG,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_u03bb] = anon_sym_u03bb,
  [anon_sym_u2200] = anon_sym_u2200,
  [anon_sym_u2203_BANG] = anon_sym_u2203_BANG,
  [anon_sym_u2203] = anon_sym_u2203,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_case] = anon_sym_case,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_od] = anon_sym_od,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_T] = anon_sym_T,
  [anon_sym_F] = anon_sym_F,
  [sym_antiquotation] = sym_antiquotation,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_char] = sym_char,
  [sym_type_var] = sym_type_var,
  [anon_sym_SLASH_BSLASH] = anon_sym_SLASH_BSLASH,
  [anon_sym_BSLASH_SLASH] = anon_sym_BSLASH_SLASH,
  [aux_sym_operator_token1] = aux_sym_operator_token1,
  [aux_sym_operator_token2] = aux_sym_operator_token2,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_binder] = sym_binder,
  [sym_keyword] = sym_keyword,
  [sym_boolean] = sym_boolean,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u03bb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2200] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2203_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u2203] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_case] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_od] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_T] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [sym_antiquotation] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_type_var] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_operator_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_operator_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_binder] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
};

static const TSCharacterRange aux_sym_operator_token2_character_set_1[] = {
  {0xac, 0xac}, {0xb7, 0xb7}, {0xd7, 0xd7}, {0x2190, 0x2190}, {0x2192, 0x2192}, {0x2194, 0x2194}, {0x21a6, 0x21a6}, {0x21d2, 0x21d2},
  {0x21d4, 0x21d4}, {0x2208, 0x2209}, {0x2218, 0x2218}, {0x2227, 0x222a}, {0x2260, 0x2261}, {0x2264, 0x2265}, {0x2282, 0x2282}, {0x2286, 0x2286},
  {0x2295, 0x2295}, {0x2297, 0x2297}, {0x22a2, 0x22a2},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 10,
        '"', 1,
        '#', 31,
        '\'', 6,
        '(', 37,
        ')', 38,
        ',', 43,
        '/', 32,
        '0', 20,
        ';', 44,
        '?', 12,
        '@', 13,
        '[', 39,
        '\\', 14,
        ']', 40,
        '^', 34,
        '{', 41,
        '}', 42,
        0x3bb, 15,
        0x2200, 16,
        0x2203, 18,
      );
      if ((0x3b1 <= lookahead && lookahead <= 0x3b4)) ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('$' <= lookahead && lookahead <= '>') ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(33);
      if (set_contains(aux_sym_operator_token2_character_set_1, 19, lookahead)) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(22);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 6:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 8:
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_QMARK_BANG);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_QMARK);
      if (lookahead == '!') ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '/') ADVANCE(30);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_u03bb);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_u2200);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_u2203_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_u2203);
      if (lookahead == '!') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_antiquotation);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(3);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_type_var);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_type_var);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SLASH_BSLASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BSLASH_SLASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_operator_token1);
      if (lookahead == '"') ADVANCE(2);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_operator_token1);
      if (lookahead == '\\') ADVANCE(29);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_operator_token1);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_operator_token1);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          ('<' <= lookahead && lookahead <= '>') ||
          lookahead == '^' ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_operator_token2);
      if (set_contains(aux_sym_operator_token2_character_set_1, 19, lookahead)) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'F', 1,
        'T', 2,
        'a', 3,
        'c', 4,
        'd', 5,
        'e', 6,
        'i', 7,
        'l', 8,
        'o', 9,
        't', 10,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_T);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(19);
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_od);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == 'h') ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_case);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0, .external_lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_QMARK_BANG] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_u03bb] = ACTIONS(1),
    [anon_sym_u2200] = ACTIONS(1),
    [anon_sym_u2203_BANG] = ACTIONS(1),
    [anon_sym_u2203] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_case] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_od] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_T] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [sym_antiquotation] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_type_var] = ACTIONS(1),
    [anon_sym_SLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_SLASH] = ACTIONS(1),
    [aux_sym_operator_token1] = ACTIONS(1),
    [aux_sym_operator_token2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(9),
    [sym__token] = STATE(2),
    [sym_binder] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_punctuation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_QMARK_BANG] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(11),
    [anon_sym_u03bb] = ACTIONS(9),
    [anon_sym_u2200] = ACTIONS(9),
    [anon_sym_u2203_BANG] = ACTIONS(9),
    [anon_sym_u2203] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_then] = ACTIONS(13),
    [anon_sym_else] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_and] = ACTIONS(13),
    [anon_sym_case] = ACTIONS(13),
    [anon_sym_of] = ACTIONS(13),
    [anon_sym_do] = ACTIONS(13),
    [anon_sym_od] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_T] = ACTIONS(15),
    [anon_sym_F] = ACTIONS(15),
    [sym_antiquotation] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [sym_char] = ACTIONS(17),
    [sym_type_var] = ACTIONS(17),
    [anon_sym_SLASH_BSLASH] = ACTIONS(19),
    [anon_sym_BSLASH_SLASH] = ACTIONS(19),
    [aux_sym_operator_token1] = ACTIONS(21),
    [aux_sym_operator_token2] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__token] = STATE(3),
    [sym_binder] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_QMARK_BANG] = ACTIONS(9),
    [anon_sym_QMARK] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_BSLASH] = ACTIONS(11),
    [anon_sym_u03bb] = ACTIONS(9),
    [anon_sym_u2200] = ACTIONS(9),
    [anon_sym_u2203_BANG] = ACTIONS(9),
    [anon_sym_u2203] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_then] = ACTIONS(13),
    [anon_sym_else] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_in] = ACTIONS(13),
    [anon_sym_and] = ACTIONS(13),
    [anon_sym_case] = ACTIONS(13),
    [anon_sym_of] = ACTIONS(13),
    [anon_sym_do] = ACTIONS(13),
    [anon_sym_od] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_T] = ACTIONS(15),
    [anon_sym_F] = ACTIONS(15),
    [sym_antiquotation] = ACTIONS(29),
    [sym_number] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [sym_char] = ACTIONS(29),
    [sym_type_var] = ACTIONS(29),
    [anon_sym_SLASH_BSLASH] = ACTIONS(19),
    [anon_sym_BSLASH_SLASH] = ACTIONS(19),
    [aux_sym_operator_token1] = ACTIONS(21),
    [aux_sym_operator_token2] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(23),
    [anon_sym_SEMI] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__token] = STATE(3),
    [sym_binder] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(36),
    [anon_sym_QMARK_BANG] = ACTIONS(36),
    [anon_sym_QMARK] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(36),
    [anon_sym_BSLASH] = ACTIONS(39),
    [anon_sym_u03bb] = ACTIONS(36),
    [anon_sym_u2200] = ACTIONS(36),
    [anon_sym_u2203_BANG] = ACTIONS(36),
    [anon_sym_u2203] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(42),
    [anon_sym_then] = ACTIONS(42),
    [anon_sym_else] = ACTIONS(42),
    [anon_sym_let] = ACTIONS(42),
    [anon_sym_in] = ACTIONS(42),
    [anon_sym_and] = ACTIONS(42),
    [anon_sym_case] = ACTIONS(42),
    [anon_sym_of] = ACTIONS(42),
    [anon_sym_do] = ACTIONS(42),
    [anon_sym_od] = ACTIONS(42),
    [anon_sym_with] = ACTIONS(42),
    [anon_sym_T] = ACTIONS(45),
    [anon_sym_F] = ACTIONS(45),
    [sym_antiquotation] = ACTIONS(48),
    [sym_number] = ACTIONS(48),
    [sym_string] = ACTIONS(48),
    [sym_char] = ACTIONS(48),
    [sym_type_var] = ACTIONS(48),
    [anon_sym_SLASH_BSLASH] = ACTIONS(51),
    [anon_sym_BSLASH_SLASH] = ACTIONS(51),
    [aux_sym_operator_token1] = ACTIONS(54),
    [aux_sym_operator_token2] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_RBRACK] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_SEMI] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_identifier] = ACTIONS(62),
    [anon_sym_BANG] = ACTIONS(60),
    [anon_sym_QMARK_BANG] = ACTIONS(60),
    [anon_sym_QMARK] = ACTIONS(62),
    [anon_sym_AT] = ACTIONS(60),
    [anon_sym_BSLASH] = ACTIONS(62),
    [anon_sym_u03bb] = ACTIONS(60),
    [anon_sym_u2200] = ACTIONS(60),
    [anon_sym_u2203_BANG] = ACTIONS(60),
    [anon_sym_u2203] = ACTIONS(62),
    [anon_sym_if] = ACTIONS(62),
    [anon_sym_then] = ACTIONS(62),
    [anon_sym_else] = ACTIONS(62),
    [anon_sym_let] = ACTIONS(62),
    [anon_sym_in] = ACTIONS(62),
    [anon_sym_and] = ACTIONS(62),
    [anon_sym_case] = ACTIONS(62),
    [anon_sym_of] = ACTIONS(62),
    [anon_sym_do] = ACTIONS(62),
    [anon_sym_od] = ACTIONS(62),
    [anon_sym_with] = ACTIONS(62),
    [anon_sym_T] = ACTIONS(62),
    [anon_sym_F] = ACTIONS(62),
    [sym_antiquotation] = ACTIONS(60),
    [sym_number] = ACTIONS(60),
    [sym_string] = ACTIONS(60),
    [sym_char] = ACTIONS(60),
    [sym_type_var] = ACTIONS(60),
    [anon_sym_SLASH_BSLASH] = ACTIONS(60),
    [anon_sym_BSLASH_SLASH] = ACTIONS(60),
    [aux_sym_operator_token1] = ACTIONS(62),
    [aux_sym_operator_token2] = ACTIONS(60),
    [anon_sym_LPAREN] = ACTIONS(60),
    [anon_sym_RPAREN] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(60),
    [anon_sym_RBRACK] = ACTIONS(60),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_COMMA] = ACTIONS(60),
    [anon_sym_SEMI] = ACTIONS(60),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
    [anon_sym_BANG] = ACTIONS(64),
    [anon_sym_QMARK_BANG] = ACTIONS(64),
    [anon_sym_QMARK] = ACTIONS(66),
    [anon_sym_AT] = ACTIONS(64),
    [anon_sym_BSLASH] = ACTIONS(66),
    [anon_sym_u03bb] = ACTIONS(64),
    [anon_sym_u2200] = ACTIONS(64),
    [anon_sym_u2203_BANG] = ACTIONS(64),
    [anon_sym_u2203] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(66),
    [anon_sym_then] = ACTIONS(66),
    [anon_sym_else] = ACTIONS(66),
    [anon_sym_let] = ACTIONS(66),
    [anon_sym_in] = ACTIONS(66),
    [anon_sym_and] = ACTIONS(66),
    [anon_sym_case] = ACTIONS(66),
    [anon_sym_of] = ACTIONS(66),
    [anon_sym_do] = ACTIONS(66),
    [anon_sym_od] = ACTIONS(66),
    [anon_sym_with] = ACTIONS(66),
    [anon_sym_T] = ACTIONS(66),
    [anon_sym_F] = ACTIONS(66),
    [sym_antiquotation] = ACTIONS(64),
    [sym_number] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_char] = ACTIONS(64),
    [sym_type_var] = ACTIONS(64),
    [anon_sym_SLASH_BSLASH] = ACTIONS(64),
    [anon_sym_BSLASH_SLASH] = ACTIONS(64),
    [aux_sym_operator_token1] = ACTIONS(66),
    [aux_sym_operator_token2] = ACTIONS(64),
    [anon_sym_LPAREN] = ACTIONS(64),
    [anon_sym_RPAREN] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(64),
    [anon_sym_RBRACK] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(64),
    [anon_sym_RBRACE] = ACTIONS(64),
    [anon_sym_COMMA] = ACTIONS(64),
    [anon_sym_SEMI] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(68),
    [sym_identifier] = ACTIONS(70),
    [anon_sym_BANG] = ACTIONS(68),
    [anon_sym_QMARK_BANG] = ACTIONS(68),
    [anon_sym_QMARK] = ACTIONS(70),
    [anon_sym_AT] = ACTIONS(68),
    [anon_sym_BSLASH] = ACTIONS(70),
    [anon_sym_u03bb] = ACTIONS(68),
    [anon_sym_u2200] = ACTIONS(68),
    [anon_sym_u2203_BANG] = ACTIONS(68),
    [anon_sym_u2203] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(70),
    [anon_sym_then] = ACTIONS(70),
    [anon_sym_else] = ACTIONS(70),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_in] = ACTIONS(70),
    [anon_sym_and] = ACTIONS(70),
    [anon_sym_case] = ACTIONS(70),
    [anon_sym_of] = ACTIONS(70),
    [anon_sym_do] = ACTIONS(70),
    [anon_sym_od] = ACTIONS(70),
    [anon_sym_with] = ACTIONS(70),
    [anon_sym_T] = ACTIONS(70),
    [anon_sym_F] = ACTIONS(70),
    [sym_antiquotation] = ACTIONS(68),
    [sym_number] = ACTIONS(68),
    [sym_string] = ACTIONS(68),
    [sym_char] = ACTIONS(68),
    [sym_type_var] = ACTIONS(68),
    [anon_sym_SLASH_BSLASH] = ACTIONS(68),
    [anon_sym_BSLASH_SLASH] = ACTIONS(68),
    [aux_sym_operator_token1] = ACTIONS(70),
    [aux_sym_operator_token2] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(68),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_LBRACK] = ACTIONS(68),
    [anon_sym_RBRACK] = ACTIONS(68),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_COMMA] = ACTIONS(68),
    [anon_sym_SEMI] = ACTIONS(68),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(72),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_BANG] = ACTIONS(72),
    [anon_sym_QMARK_BANG] = ACTIONS(72),
    [anon_sym_QMARK] = ACTIONS(74),
    [anon_sym_AT] = ACTIONS(72),
    [anon_sym_BSLASH] = ACTIONS(74),
    [anon_sym_u03bb] = ACTIONS(72),
    [anon_sym_u2200] = ACTIONS(72),
    [anon_sym_u2203_BANG] = ACTIONS(72),
    [anon_sym_u2203] = ACTIONS(74),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_then] = ACTIONS(74),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_let] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_and] = ACTIONS(74),
    [anon_sym_case] = ACTIONS(74),
    [anon_sym_of] = ACTIONS(74),
    [anon_sym_do] = ACTIONS(74),
    [anon_sym_od] = ACTIONS(74),
    [anon_sym_with] = ACTIONS(74),
    [anon_sym_T] = ACTIONS(74),
    [anon_sym_F] = ACTIONS(74),
    [sym_antiquotation] = ACTIONS(72),
    [sym_number] = ACTIONS(72),
    [sym_string] = ACTIONS(72),
    [sym_char] = ACTIONS(72),
    [sym_type_var] = ACTIONS(72),
    [anon_sym_SLASH_BSLASH] = ACTIONS(72),
    [anon_sym_BSLASH_SLASH] = ACTIONS(72),
    [aux_sym_operator_token1] = ACTIONS(74),
    [aux_sym_operator_token2] = ACTIONS(72),
    [anon_sym_LPAREN] = ACTIONS(72),
    [anon_sym_RPAREN] = ACTIONS(72),
    [anon_sym_LBRACK] = ACTIONS(72),
    [anon_sym_RBRACK] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(72),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_COMMA] = ACTIONS(72),
    [anon_sym_SEMI] = ACTIONS(72),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(76),
    [sym_identifier] = ACTIONS(78),
    [anon_sym_BANG] = ACTIONS(76),
    [anon_sym_QMARK_BANG] = ACTIONS(76),
    [anon_sym_QMARK] = ACTIONS(78),
    [anon_sym_AT] = ACTIONS(76),
    [anon_sym_BSLASH] = ACTIONS(78),
    [anon_sym_u03bb] = ACTIONS(76),
    [anon_sym_u2200] = ACTIONS(76),
    [anon_sym_u2203_BANG] = ACTIONS(76),
    [anon_sym_u2203] = ACTIONS(78),
    [anon_sym_if] = ACTIONS(78),
    [anon_sym_then] = ACTIONS(78),
    [anon_sym_else] = ACTIONS(78),
    [anon_sym_let] = ACTIONS(78),
    [anon_sym_in] = ACTIONS(78),
    [anon_sym_and] = ACTIONS(78),
    [anon_sym_case] = ACTIONS(78),
    [anon_sym_of] = ACTIONS(78),
    [anon_sym_do] = ACTIONS(78),
    [anon_sym_od] = ACTIONS(78),
    [anon_sym_with] = ACTIONS(78),
    [anon_sym_T] = ACTIONS(78),
    [anon_sym_F] = ACTIONS(78),
    [sym_antiquotation] = ACTIONS(76),
    [sym_number] = ACTIONS(76),
    [sym_string] = ACTIONS(76),
    [sym_char] = ACTIONS(76),
    [sym_type_var] = ACTIONS(76),
    [anon_sym_SLASH_BSLASH] = ACTIONS(76),
    [anon_sym_BSLASH_SLASH] = ACTIONS(76),
    [aux_sym_operator_token1] = ACTIONS(78),
    [aux_sym_operator_token2] = ACTIONS(76),
    [anon_sym_LPAREN] = ACTIONS(76),
    [anon_sym_RPAREN] = ACTIONS(76),
    [anon_sym_LBRACK] = ACTIONS(76),
    [anon_sym_RBRACK] = ACTIONS(76),
    [anon_sym_LBRACE] = ACTIONS(76),
    [anon_sym_RBRACE] = ACTIONS(76),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binder, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binder, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_comment = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_holterm_external_scanner_create(void);
void tree_sitter_holterm_external_scanner_destroy(void *);
bool tree_sitter_holterm_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_holterm_external_scanner_serialize(void *, char *);
void tree_sitter_holterm_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_holterm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_holterm_external_scanner_create,
      tree_sitter_holterm_external_scanner_destroy,
      tree_sitter_holterm_external_scanner_scan,
      tree_sitter_holterm_external_scanner_serialize,
      tree_sitter_holterm_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
